### ISSUE TITLE
Start and the end and work backward

### ISSUE THREAD

**Issue by oubiwann** [hexagram30/client#19]
The code in the client repo has been created as part of following along with the [Rust roguelike Tutorial](http://bfnightly.bracketproductions.com/rustbook/), with serious modifications. A more recent change to add level support combined with the configuration system resulted in a bug that crashed the game after load-up. A few weeks of debugging didn't reveal the root cause.

Furthermore, later in the tutorial a whole series of optimizations are made. We want to take advantage of those now and not later.

Sub-tickets:
* [x] Use chapter 73 as the basis for an update to the client - #20
* [ ] Rename the project library name - #23
* [ ] Add configuration support to new base branch - #21
* [ ] Remove all web assembly code in new base branch - #22
* More to come ...
